name: backend_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  shelf_router: ^1.0.0
  shelf: ^1.4.0
  qr_flutter: ^4.0.0
  mysql1: ^0.20.0
  stack_trace: ^1.12.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
